In [1]:
import numpy.matlib 
import numpy as np 

a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [2]:
a

array([[1, 2],
       [3, 4]])

In [3]:
b

array([[11, 12],
       [13, 14]])

In [5]:
a[0]

array([1, 2])

In [6]:
a[1]

array([3, 4])

In [7]:
np.dot(a[0], a[1])

11

In [8]:
a

array([[1, 2],
       [3, 4]])

In [9]:
b

array([[11, 12],
       [13, 14]])

In [10]:
np.dot(a[0], b[0])

35