In [1]:
import numpy as np
import pandas as pd

In [18]:
# This data comes from the Figure 3.7 from book (page 95)

data = np.array([
    [1, 1, 1, 0, 0, 0],
    [1, 1, 1, 0, 0, 0],
    [1, 1, 1, 0, 0, 0],
    [1, 1, 1, 1, 1, 1],
    [-1, -1, -1, 1, 1, 1],
    [-1, -1, 1, 1, 1, 1],
    [-1, -1, -1, 1, 1, 1]
])

In [21]:
data = data.astype('float')

In [22]:
from scipy.sparse.linalg import svds

In [25]:
U, sigma, Vt = svds(data, k = 2)

In [26]:
U

array([[-0.24950758, -0.33765778],
       [-0.24950758, -0.33765778],
       [-0.24950758, -0.33765778],
       [-0.70048332, -0.16401663],
       [-0.20146817,  0.51129892],
       [-0.4913066 ,  0.3289484 ],
       [-0.20146817,  0.51129892]])

In [29]:
sigma = np.diag(sigma)
sigma

array([[3.25707011, 0.        ],
       [0.        , 4.52956534]])

In [28]:
Vt

array([[-0.17032582, -0.17032582, -0.47201204, -0.48961987, -0.48961987,
        -0.48961987],
       [-0.55822932, -0.55822932, -0.41298431,  0.26217297,  0.26217297,
         0.26217297]])

In [31]:
data_recreated = np.dot(np.dot(U, sigma), Vt)

In [35]:
data_recreated

array([[ 0.99219751,  0.99219751,  1.01522298, -0.00308232, -0.00308232,
        -0.00308232],
       [ 0.99219751,  0.99219751,  1.01522298, -0.00308232, -0.00308232,
        -0.00308232],
       [ 0.99219751,  0.99219751,  1.01522298, -0.00308232, -0.00308232,
        -0.00308232],
       [ 0.8033243 ,  0.8033243 ,  1.38372244,  0.92230455,  0.92230455,
         0.92230455],
       [-1.18107072, -1.18107072, -0.64672352,  0.92846919,  0.92846919,
         0.92846919],
       [-0.55919915, -0.55919915,  0.13997929,  1.1741355 ,  1.1741355 ,
         1.1741355 ],
       [-1.18107072, -1.18107072, -0.64672352,  0.92846919,  0.92846919,
         0.92846919]])

In [32]:
U, sigma, Vt = svds(data_recreated, k = 2)

In [33]:
sigma = np.diag(sigma)

In [34]:
np.dot(np.dot(U, sigma), Vt)

array([[ 0.99219751,  0.99219751,  1.01522298, -0.00308232, -0.00308232,
        -0.00308232],
       [ 0.99219751,  0.99219751,  1.01522298, -0.00308232, -0.00308232,
        -0.00308232],
       [ 0.99219751,  0.99219751,  1.01522298, -0.00308232, -0.00308232,
        -0.00308232],
       [ 0.8033243 ,  0.8033243 ,  1.38372244,  0.92230455,  0.92230455,
         0.92230455],
       [-1.18107072, -1.18107072, -0.64672352,  0.92846919,  0.92846919,
         0.92846919],
       [-0.55919915, -0.55919915,  0.13997929,  1.1741355 ,  1.1741355 ,
         1.1741355 ],
       [-1.18107072, -1.18107072, -0.64672352,  0.92846919,  0.92846919,
         0.92846919]])